name: auto-build-deploy
on:
  push:
    branches:
      - "iter4-master"
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: checking allow to build
        run: |
          if [ ${{secrets.BUILD}} == ACTIVE ]
          then
            echo '------------------- ready to deploy --------------------'
          else
            echo 'not ready'
            exit 1
          fi
  build-push:
    needs: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Check if Docker Buildx is installed
        id: check
        run: |
          ls
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build and Push Docker Image
        run: |
          composer install  # If you need to install Laravel dependencies
          ./vendor/bin/sail build
          docker tag sail-8.2/app:latest "heaty566/huy-tung-server:latest"
          docker login -u ${{ secrets.DOCKER_USERNAME  }} -p ${{ secrets.DOCKER_ACCESS_TOKEN  }}
          docker push heaty566/huy-tung-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/app/huy-tung
            sudo docker-compose pull
            sudo docker-compose up -d
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
